version: "3.8"
services:
  tr-search-db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: tr-database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api-tr:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_HOST: tr-search-db
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: tr-database
      DB_PORT: 5432
    depends_on:
      - tr-search-db

volumes:
  postgres_data:
