spring.datasource.url=jdbc:postgresql://otto.db.elephantsql.com:5432/tijdifzw?createDatabaseIfNotExist=true
spring.datasource.username=tijdifzw
spring.datasource.password=4_eH7yHw-4z-F_m-A6yOJ67jgti5PcZo
