CREATE TABLE establishments (
    id UUID PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    photo VARCHAR(255),
    description TEXT NOT NULL,
    telephone VARCHAR(20) NOT NULL,
    cellphone VARCHAR(20) NOT NULL,
    email VARCHAR NOT NULL,
    category VARCHAR(20) NOT NULL,
    code VARCHAR(255) NOT NULL,
    status BOOLEAN NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    picture1 VARCHAR(255),
    picture2 VARCHAR(255),
    picture3 VARCHAR(255),
    picture4 VARCHAR(255),
    picture5 VARCHAR(255),
    picture6 VARCHAR(255),
    picture7 VARCHAR(255),
    picture8 VARCHAR(255),
    picture9 VARCHAR(255),
    picture10 VARCHAR(255)
);
